<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.js"></script>
	<title>Dummy sample rest api</title>
	<style>
	.thead-inverse th {
    color: #fff;
    background-color: #373a3c;
}
	</style>
</head>
<body>
	<div class="container" style="margin:50px;">
		<h1>Welcome Dummy api example</h1>
		
		</div>
	</body>
</html>